version: 2.1
orbs:
  architect: giantswarm/architect@4.10.1

# external cluster is used because tests use
# docker cp.
# otherwise the kind cluster containers and the
# container of app-test-suite cannot work together
jobs:
  test:
    machine: true
    environment:
      KIND_VERSION: v0.11.1
      KUBERNETES_VERSION: v1.21.1
    steps:
      - checkout
      - run:
          name: Download kind
          command: |
            curl -sLo kind https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/bin
      - run:
          name: Spin up cluster
          command: |
            kind create cluster --config tests/kind_config.yaml --kubeconfig kind.kube.config
      - architect/run-tests-with-ats:
          chart_archive_prefix: "cert-exporter"
          app-test-suite_version: "v0.2.2"
          app-test-suite_container_tag: "0.2.2"
          additional_app-test-suite_flags: "--external-cluster-version $KUBERNETES_VERSION"

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: cert-exporter
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-cert-exporter-to-quay
          image: "quay.io/giantswarm/cert-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-cert-exporter-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          executor: app-build-suite
          name: push-cert-exporter-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "cert-exporter"
          requires:
            - push-cert-exporter-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          executor: app-build-suite
          name: push-cert-exporter-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cert-exporter"
          requires:
            - push-cert-exporter-to-quay
          persist_chart_archive: true
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - hold-push-cert-exporter-to-aliyun-pr:
          type: approval
          requires:
            - build
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

      - architect/push-to-docker:
          context: architect
          name: push-cert-exporter-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - hold-push-cert-exporter-to-aliyun-pr
          # Needed to prevent job being triggered for master branch.
          filters:
            branches:
              ignore: master

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker:
          name: push-cert-exporter-to-aliyun-master
          context: architect
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-shared-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-aws-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-openstack-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "openstack-app-collection"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-azure-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-kvm-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-vmware-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - test:
          name: execute tests
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          # resource_class: xlarge
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - master
            tags:
              ignore: /^v.*/
