version: 2.1
orbs:
  architect: giantswarm/architect@0.10.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: cert-exporter
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-cert-exporter-to-quay
          image: "quay.io/giantswarm/cert-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-cert-exporter-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on git tag.
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-cert-exporter-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "cert-exporter"
          requires:
            - push-cert-exporter-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-cert-exporter-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cert-exporter"
          requires:
            - push-cert-exporter-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - hold-push-cert-exporter-to-aliyun-pr:
          type: approval
          requires:
            - build
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master

      - architect/push-to-docker-legacy:
          name: push-cert-exporter-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - hold-push-cert-exporter-to-aliyun-pr
          # Needed to prevent job being triggered for master branch.
          filters:
            branches:
              ignore: master

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker-legacy:
          name: push-cert-exporter-to-aliyun-master
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cert-exporter"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              only: master

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-aws-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          unique: "true"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-azure-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          unique: "true"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-cert-exporter-to-kvm-app-collection
          app_name: "cert-exporter"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          unique: "true"
          requires:
            - push-cert-exporter-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
