version: 2.1

orbs:
  architect: giantswarm/architect@6.7.0

jobs:
  test:
    machine:
      image: ubuntu-2404:current
    environment:
      KIND_VERSION: v0.24.0
      KUBERNETES_VERSION: v1.29.2
    steps:
      - checkout
      - run:
          name: Install KIND
          command: sudo curl --fail --location "https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64" --output /usr/bin/kind && sudo chmod +x /usr/bin/kind
      - run:
          name: Create cluster
          command: kind create cluster --image "kindest/node:${KUBERNETES_VERSION}" --config tests/cluster.yaml --kubeconfig kind.kube.config
      - architect/run-tests-with-ats:
          chart_archive_prefix: cert-exporter
          app-test-suite_version: v0.10.2
          app-test-suite_container_tag: 0.10.2
          additional_app-test-suite_flags: --external-cluster-version "${KUBERNETES_VERSION}"

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: cert-exporter
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          name: push-to-registries
          context: architect
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-default-catalog
          context: architect
          executor: app-build-suite
          chart: cert-exporter
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          persist_chart_archive: true
          requires:
            - push-to-registries
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          executor: app-build-suite
          chart: cert-exporter
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          requires:
            - push-to-registries
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - test:
          name: run-tests-with-ats
          requires:
            - push-to-default-catalog
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/
