exporter:
  certPath: "/etc/kubernetes/ssl"
  tokenPath: ""
  namespace: monitoring

image:
  repository: giantswarm/cert-exporter
  tag: "[[ .Version ]]"

registry:
  domain: docker.io

vaultAddress: ""
