exporter:
  certPath: ""
  tokenPath: ""

image:
  repository: giantswarm/cert-exporter
  tag: ""

registry:
  domain: docker.io

vaultAddress: ""

# This can be removed in versions > 2.0.0
fixJob:
  enabled: true
