config:
  deployment:
    monitorCertificates: true
    monitorFiles: false
    monitorSecrets: true
  daemonset:
    monitorCertificates: false
    monitorFiles: true
    monitorSecrets: false

exporter:
  certPath: ""
  capiCertPath: ""
  tokenPath: ""

image:
  repository: giantswarm/cert-exporter
  tag: ""

registry:
  domain: docker.io

vaultAddress: ""

ciliumNetworkPolicy:
  enabled: false
