config:
  deployment:
    monitorCertificates: true
    monitorFiles: false
    monitorSecrets: true
  daemonset:
    monitorCertificates: false
    monitorFiles: true
    monitorSecrets: false

exporter:
  certPath: ""
  capiCertPath: ""
  tokenPath: ""

# Enable Kyverno Policy Exceptions
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

image:
  repository: giantswarm/cert-exporter
  tag: ""

registry:
  domain: gsoci.azurecr.io

vaultAddress: ""

ciliumNetworkPolicy:
  enabled: false

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"

global:
  podSecurityStandards:
    enforced: false

deployment:
  autoscaling:
    # -- Lower bounds for vertical autoscaling.
    minAllowed:
      cpu: 50m
      memory: 50Mi
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 150m
      memory: 150Mi

daemonset:
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 150m
      memory: 50Mi
