{{- if .Values.fixJob.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "certExporter.fixJob" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "certExporter.fixJobAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "certExporter.fixJob" . | quote }}
    {{- include "certExporter.fixJobSelectorLabels" . | nindent 4 }}
    role: {{ include "certExporter.fixJobSelector" . | quote }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - list
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - delete
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - list
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - delete
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "certExporter.fixJob" . }}
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "certExporter.fixJob" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "certExporter.fixJobAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "certExporter.fixJob" . | quote }}
    {{- include "certExporter.fixJobSelectorLabels" . | nindent 4 }}
    role: {{ include "certExporter.fixJobSelector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "certExporter.fixJob" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "certExporter.fixJob" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
