{{- if and .Release.IsUpgrade .Values.fixJob.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "certExporter.fixJob" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "certExporter.fixJobAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "certExporter.fixJob" . | quote }}
    {{- include "certExporter.fixJobSelectorLabels" . | nindent 4 }}
    role: {{ include "certExporter.fixJobSelector" . | quote }}
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'secret'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}
