{{- if .Values.waitJob.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "certExporter.waitJob" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "certExporter.waitJobAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "certExporter.waitJob" . | quote }}
    {{- include "certExporter.waitJobSelectorLabels" . | nindent 4 }}
    role: {{ include "certExporter.waitJobSelector" . | quote }}
{{- end }}
