{{- if .Values.waitJob.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "certExporter.waitJob" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "certExporter.waitJobAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "certExporter.waitJob" . | quote }}
    {{- include "certExporter.waitJobSelectorLabels" . | nindent 4 }}
    role: {{ include "certExporter.waitJobSelector" . | quote }}
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
  - 'secret'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
{{- end }}
