apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cert-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: cert-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: cert-exporter
      labels:
        app: cert-exporter
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      tolerations:
      # Tolerate master taint
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: cert-exporter
      containers:
      - name: cert-exporter
        image: quay.io/giantswarm/cert-exporter:[[ .SHA ]]
        args:
        - --vault-url={{ .Values.Installation.V1.Auth.Vault.Address }}
        ports:
        - name: cert-exporter
          containerPort: 9005
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/ssl
          name: certs-volume
        - mountPath: /etc/tokens
          name: tokens-volume
        - mountPath: /etc/ssl/certs/
          name: ca-certs
      volumes:
      - name: certs-volume
        hostPath:
          path: /etc/kubernetes/ssl
      - name: tokens-volume
        hostPath:
          path: /etc/tokens
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs/
      hostNetwork: true
      hostPID: true
