apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cert-exporter
  namespace: monitoring
  labels:
    app: cert-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: cert-exporter
      labels:
        app: cert-exporter
    spec:
      tolerations:
      # Tolerate master taint
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: cert-exporter
        image: quay.io/giantswarm/cert-exporter:[[ .SHA ]]
        args:
        - --path=/etc/kubernetes/ssl
        ports:
        - name: cert-exporter
          containerPort: 8000
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/kubernetes/ssl
          name: host-volume
      volumes:
      - name: host-volume
        hostPath:
          path: /etc/kubernetes/ssl
      imagePullSecrets:
      - name: cert-exporter-pull-secret
