apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}-psp
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535i
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  hostPorts:
  - max: 9005
    min: 9005
  volumes:
    - 'secret'
    - 'hostPath'
  hostNetwork: true
  hostIPC: false
  hostPID: true
