{{- if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ template "certExporter.daemonset.name" . }}-policy-exceptions
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - host-ports-none
    - autogen-host-ports-none
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: disallow-privilege-escalation
    ruleNames:
    - autogen-privilege-escalation
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
  - policyName: disallow-capabilities-strict
    ruleNames:
    - autogen-require-drop-all

  match:
    any:
    - resources:
        kinds:
        - DaemonSet
        - ReplicaSet
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ template "certExporter.daemonset.name" . }}*
{{- end }}
