apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: "{{ template "certExporter.daemonset.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "certExporter.daemonset.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "certExporter.daemonset.labels" . | nindent 8 }}
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
    spec:
      tolerations:
      # Tolerate all taints for observability
      - operator: "Exists"
      serviceAccountName: "{{ template "certExporter.daemonset.name" . }}"
      priorityClassName: giantswarm-critical
      containers:
      - name: cert-exporter
        image: {{ include "certExporter.containerImage" . | quote }}
        args:
        - --monitor-secrets=false
        - --monitor-certificates=false
        - --monitor-files=true
        - --cert-paths={{ default "/etc/kubernetes/ssl" .Values.exporter.certPath }}
        {{ if ne .Values.exporter.tokenPath "" }}
        - --token-path={{ .Values.exporter.tokenPath }}
        {{ end }}
        {{ if ne .Values.vaultAddress "" }}
        - --vault-url={{ .Values.vaultAddress }}
        {{ end }}
        ports:
        - name: cert-exporter
          containerPort: 9005
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - mountPath: {{ default "/etc/kubernetes/ssl" .Values.exporter.certPath }}
          name: certs-volume
          readOnly: true
        {{ if ne .Values.exporter.tokenPath "" }}
        - mountPath: {{ .Values.exporter.tokenPath }}
          name: tokens-volume
          readOnly: true
        {{ end }}
        - mountPath: /etc/ssl/certs/
          name: ca-certs
          readOnly: true
      volumes:
      - name: certs-volume
        hostPath:
          path: {{ default "/etc/kubernetes/ssl" .Values.exporter.certPath }}
      {{ if ne .Values.exporter.tokenPath "" }}
      - name: tokens-volume
        hostPath:
          path: {{ .Values.exporter.tokenPath }}
      {{ end }}
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs/
