apiVersion: apps/v1
kind: Deployment
metadata :
  name: "{{ template "certExporter.deployment.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certExporter.deployment.labels" . | nindent 4 }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "certExporter.deployment.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "certExporter.deployment.labels" . | nindent 8 }}
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      serviceAccountName: "{{ template "certExporter.deployment.name" . }}"
      priorityClassName: giantswarm-critical
      containers:
      - name: cert-exporter
        image: {{ include "certExporter.containerImage" . | quote }}
        args:
        - --monitor-secrets={{ .Values.config.deployment.monitorSecrets }}
        - --monitor-certificates={{ .Values.config.deployment.monitorCertificates }}
        - --monitor-files={{ .Values.config.deployment.monitorFiles }}
        ports:
        - name: cert-exporter
          containerPort: 9005
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
