{{ $privateSubnets := list "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ template "certExporter.deployment.name" . }}"
  labels:
    {{- include "certExporter.deployment.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "certExporter.deployment.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: 9005
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: prometheus
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: api-server
    {{ range $index, $privateSubnet := $privateSubnets }}
    - ipBlock:
        cidr: {{ $privateSubnet }}
    {{ end }}
  egress:
  - ports:
    - port: 443
      protocol: TCP
    # legacy port kept for compatibility
    - port: 6443
      protocol: TCP
    to:
    {{ range $index, $privateSubnet := $privateSubnets }}
    - ipBlock:
        cidr: {{ $privateSubnet }}
    {{- end }}
