{{ $privateSubnets := list "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ template "certExporter.daemonset.name" . }}"
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "certExporter.daemonset.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - ports:
    - port: 9005
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: prometheus
    {{ range $index, $privateSubnet := $privateSubnets }}
    - ipBlock:
        cidr: {{ $privateSubnet }}
    {{ end }}
  egress:
  - ports:
    - port: 53
      protocol: UDP
    # DNS uses TCP when the response is larger than 512 bytes
    - port: 53
      protocol: TCP
    - port: 1053
      protocol: UDP
    # DNS uses TCP when the response is larger than 512 bytes
    - port: 1053
      protocol: TCP
    # To scrape the vault token expiration
    - port: 443
      protocol: TCP
    to:
    {{ range $index, $privateSubnet := $privateSubnets }}
    - ipBlock:
        cidr: {{ $privateSubnet }}
    {{- end }}
