{{ if .Values.e2e }}
apiVersion: scheduling.k8s.io/v1beta1
description: This priority class is used by giantswarm kubernetes components.
kind: PriorityClass
metadata:
  name: giantswarm-critical
value: 1000000000
{{- end -}}
