apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: "{{ template "certExporter.deployment.name" . }}"
  labels:
    {{- include "certExporter.deployment.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser:
    ranges:
      - max: 1000
        min: 1000
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 1000
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 1000
  volumes:
    - 'secret'
    - 'hostPath'
  allowedHostPaths:
  - pathPrefix: /etc/ssl/certs/
    readOnly: true
  - pathPrefix: {{ default "/etc/kubernetes/ssl" .Values.exporter.certPath }}
    readOnly: true
  {{ if ne .Values.exporter.tokenPath "" }}
  - pathPrefix: {{ .Values.exporter.tokenPath }}
    readOnly: true
  {{ end }}
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: true
