apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cert-exporter-psp
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  runAsUser:
    ranges:
      - max: 1000
        min: 1000
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 1000
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1000
        max: 1000
  volumes:
    - 'secret'
    - 'hostPath'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  readOnlyRootFilesystem: true
