apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
      - "clusterissuers"
      - "issuers"
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-exporter
roleRef:
  kind: ClusterRole
  name: cert-exporter
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cert-exporter
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-exporter-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - cert-exporter-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-exporter-psp
subjects:
  - kind: ServiceAccount
    name: cert-exporter
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cert-exporter-psp
  apiGroup: rbac.authorization.k8s.io
