apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ template "certExporter.daemonset.name" . }}"
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policies
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - "{{ template "certExporter.daemonset.name" . }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "certExporter.daemonset.name" . }}"
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: "{{ template "certExporter.daemonset.name" . }}"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ template "certExporter.daemonset.name" . }}"
  apiGroup: rbac.authorization.k8s.io
