apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-exporter-psp
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policies
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - cert-exporter-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-exporter-psp
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: cert-exporter
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cert-exporter-psp
  apiGroup: rbac.authorization.k8s.io
