apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ template "certExporter.deployment.name" . }}"
  labels:
    {{- include "certExporter.deployment.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
      - "clusterissuers"
      - "issuers"
    verbs:
      - list
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - "{{ template "certExporter.deployment.name" . }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "certExporter.deployment.name" . }}"
  labels:
    {{- include "certExporter.deployment.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: "{{ template "certExporter.deployment.name" . }}"
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: "{{ template "certExporter.deployment.name" . }}"
    namespace: {{ .Release.Namespace }}
