{{- if .Values.daemonset.enabled }}
{{- if not .Values.global.podSecurityStandards.enforced }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ template "certExporter.daemonset.name" . }}"
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - "{{ template "certExporter.daemonset.name" . }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "certExporter.daemonset.name" . }}"
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: "{{ template "certExporter.daemonset.name" . }}"
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: "{{ template "certExporter.daemonset.name" . }}"
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
