{{- if .Values.daemonset.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "certExporter.daemonset.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
spec:
  ports:
  - name: cert-exporter
    port: 9005
    targetPort: cert-exporter
  selector:
    {{- include "certExporter.daemonset.matchLabels" . | nindent 4 }}
{{- end }}
