apiVersion: v1
kind: Service
metadata:
  name: "{{ template "certExporter.deployment.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certExporter.deployment.labels" . | nindent 4 }}
spec:
  ports:
  - name: cert-exporter
    port: 9005
    targetPort: cert-exporter
  selector:
    {{- include "certExporter.deployment.matchLabels" . | nindent 4 }}
