{{- if .Values.daemonset.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ template "certExporter.daemonset.name" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certExporter.daemonset.labels" . | nindent 4 }}
{{- end }}
