apiVersion: v1
kind: Service
metadata:
  name: secret-cert-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certExporter.deployment.labels" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
spec:
  ports:
  - name: secret-cert-exporter
    port: 9005
    targetPort: cert-exporter
  selector:
    {{- include "certExporter.deployment.matchLabels" . | nindent 4 }}
