apiVersion: v1
kind: Service
metadata:
  name: secret-cert-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: secret-cert-exporter
    giantswarm.io/monitoring: "true"
spec:
  ports:
  - name: secret-cert-exporter
    port: 9005
    targetPort: cert-exporter
  selector:
    app: secret-cert-exporter
